AllCops:
  DisplayCopNames: true

Metrics/LineLength:
  AllowURI: true
    - http
    - https
  Max: 128

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
